" Author: Yam
" Version: 0.1
" Email: haoshaochun@gmail.com
" Blog: https://yam.gift
" LastModify: 20201118


"===========================
" Basic
"===========================

set history=500

filetype plugin on
filetype indent on

let mapleader = ","



"===========================
" Edit
"===========================

set shiftwidth=4
set tabstop=4
set smarttab
set expandtab "space instead of tab
set ai "Auto indent
set si "Smart indent



"===========================
" Display
"===========================

set ruler
set hlsearch

syntax enable


"===========================
" Plugin
"===========================

" call plug#begin('~/.vim/bundle')

" call plug#end()

execute pathogen#infect()

" Syntastic
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0


" Autoformat
noremap <F3> :Autoformat<CR>

" cmd
noremap <leader>c :!./a.out
noremap <leader>cp :!g++ --std=c++17 -O2 -Wall 
noremap <leader>py :!python 



colorscheme molokai
