source /home/haoshaochun/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

antigen bundle sukkaw/zsh-proxy

# Load the theme.
antigen theme robbyrussell

# Tell Antigen that you're done.
antigen apply

. ~/z.sh
alias emacs="emacs -nw"
